# Generated by Django 4.1 on 2022-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_amenities_alter_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('entire_place', 'Entire Place'), ('private_room', 'Private Room'), ('shared_room', 'Shared Room')], max_length=20),
        ),
    ]
