# Generated by Django 4.1 on 2022-10-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='experiences',
            new_name='experience',
        ),
    ]
